# Default values for grafana
image:
  repository: grafana-python
  tag: local
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: NodePort
  port: 3000
  targetPort: 3000
  nodePort: 32000

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  storage: 0.5Gi

env:
  GF_SECURITY_ADMIN_PASSWORD: "<override this>" # Change this for prod