apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "grafana.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "grafana.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: grafana
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: {{ .Values.env.GF_SECURITY_ADMIN_PASSWORD | quote }}
        volumeMounts:
        {{- if .Values.persistence.enabled }}
        - name: grafana-storage
          mountPath: /var/lib/grafana
        {{- end }}
      volumes:
      {{- if .Values.persistence.enabled }}
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc
      {{- end }}